branch-defaults:
  aws:
    environment: flask-1-env
    group_suffix: null
  master:
    environment: flask-1-env
    group_suffix: null
global:
  application_name: ConvertNumbers
  branch: null
  default_ec2_keyname: rafarbop
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
